apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: nginx
        image: tcshackathongroup9/Spring-boot
        ports:
        - containerPort: 80
        

        
---------

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: spring
    tier: frontend
spec:

  type: NodePort

  ports:
    - port: 80
  selector:
    app: spring
    tier: frontend
